CREATE TABLE IF NOT EXISTS email_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  key TEXT UNIQUE NOT NULL,
  subject TEXT NOT NULL,
  html TEXT NOT NULL,
  description TEXT DEFAULT '',
  updated_at TIMESTAMPTZ DEFAULT now(),
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Seed initial templates
INSERT INTO email_templates (key, subject, html, description) VALUES
('welcome', 'Witamy w WitaLine — {{businessName}} jest aktywne!',
'<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f8faf8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;"><div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.06);"><div style="background:linear-gradient(135deg,#3CBF4A,#2EA03A);padding:32px;text-align:center;"><h1 style="color:white;font-size:24px;margin:0;">WitaLine</h1></div><div style="padding:32px;"><h2 style="font-size:20px;color:#171717;margin:0 0 16px;">Cześć {{businessName}}!</h2><p style="font-size:15px;color:#52525b;line-height:1.6;margin:0 0 24px;">Twoje konto zostało aktywowane. Asystent AI jest gotowy do pracy!</p><a href="{{dashboardUrl}}" style="display:inline-block;background:#3CBF4A;color:white;padding:14px 32px;border-radius:12px;font-size:15px;font-weight:600;text-decoration:none;">Przejdź do panelu →</a></div></div></body></html>',
'Email powitalny po rejestracji'),

('trial_activation', 'Twój asystent AI jest gotowy — {{businessName}}',
'<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f8faf8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;"><div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.06);"><div style="background:linear-gradient(135deg,#3CBF4A,#2EA03A);padding:32px;text-align:center;"><h1 style="color:white;font-size:24px;margin:0;">Asystent aktywny</h1></div><div style="padding:32px;"><h2 style="font-size:20px;color:#171717;margin:0 0 16px;">Cześć {{businessName}}!</h2><p style="font-size:15px;color:#52525b;line-height:1.6;margin:0 0 24px;">Twój asystent AI WitaLine jest już aktywny i gotowy do odbierania telefonów.</p><div style="background:#f0fdf4;border-radius:12px;padding:20px;margin:0 0 24px;"><p style="font-size:13px;color:#1C6323;margin:0 0 8px;font-weight:600;">Przetestuj swojego asystenta:</p><p style="font-size:24px;font-weight:700;color:#3CBF4A;margin:0 0 4px;letter-spacing:1px;">{{testNumber}}</p><p style="font-size:12px;color:#52525b;margin:0;">Zadzwoń na ten numer i sprawdź, jak asystent odpowiada na pytania o Twoją firmę.</p></div><a href="{{dashboardUrl}}" style="display:inline-block;background:#3CBF4A;color:white;padding:14px 32px;border-radius:12px;font-size:15px;font-weight:600;text-decoration:none;">Przejdź do panelu →</a></div></div></body></html>',
'Email aktywacji trial — informuje o numerze testowym'),

('first_call', 'Pierwsza rozmowa odebrana! 🎉 — {{businessName}}',
'<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f8faf8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;"><div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.06);"><div style="background:linear-gradient(135deg,#3CBF4A,#2EA03A);padding:32px;text-align:center;"><h1 style="color:white;font-size:24px;margin:0;">Pierwsza rozmowa</h1></div><div style="padding:32px;"><h2 style="font-size:20px;color:#171717;margin:0 0 16px;">Świetnie, {{businessName}}!</h2><p style="font-size:15px;color:#52525b;line-height:1.6;margin:0 0 24px;">Twój asystent AI odebrał pierwszą rozmowę! 🎉</p><a href="{{dashboardUrl}}" style="display:inline-block;background:#3CBF4A;color:white;padding:14px 32px;border-radius:12px;font-size:15px;font-weight:600;text-decoration:none;">Zobacz szczegóły →</a></div></div></body></html>',
'Gratulacje po pierwszej udanej rozmowie'),

('trial_minute_warning', 'Wykorzystałeś {{minutesUsed}} z {{maxMinutes}} minut okresu próbnego',
'<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f8faf8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;"><div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.06);"><div style="background:linear-gradient(135deg,#3CBF4A,#2EA03A);padding:32px;text-align:center;"><h1 style="color:white;font-size:24px;margin:0;">WitaLine</h1></div><div style="padding:32px;"><h2 style="font-size:20px;color:#171717;margin:0 0 16px;">Cześć {{businessName}},</h2><p style="font-size:15px;color:#52525b;line-height:1.6;margin:0 0 24px;">Wykorzystałeś już <strong>{{minutesUsed}} z {{maxMinutes}} minut</strong> w okresie próbnym. Pozostało Ci około <strong>{{remaining}} minut</strong> darmowych rozmów.</p><a href="{{dashboardUrl}}" style="display:inline-block;background:#3CBF4A;color:white;padding:14px 32px;border-radius:12px;font-size:15px;font-weight:600;text-decoration:none;">Doładuj konto →</a></div></div></body></html>',
'Ostrzeżenie przy 80% użycia minuty trial'),

('trial_expired', 'Okres próbny WitaLine wygasł — doładuj konto, aby kontynuować',
'<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f8faf8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;"><div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.06);"><div style="background:linear-gradient(135deg,#EF4444,#DC2626);padding:32px;text-align:center;"><h1 style="color:white;font-size:24px;margin:0;">Okres próbny zakończony</h1></div><div style="padding:32px;"><h2 style="font-size:20px;color:#171717;margin:0 0 16px;">Cześć {{businessName}},</h2><p style="font-size:15px;color:#52525b;line-height:1.6;margin:0 0 24px;">Twój okres próbny w WitaLine dobiegł końca. Asystent AI przestał odbierać telefony.</p><p style="font-size:15px;color:#52525b;line-height:1.6;margin:0 0 24px;">Cena już od <strong>1,00 PLN/min brutto</strong>. Nie potrzebujesz abonamentu.</p><a href="{{dashboardUrl}}" style="display:inline-block;background:#3CBF4A;color:white;padding:14px 32px;border-radius:12px;font-size:15px;font-weight:600;text-decoration:none;">Doładuj konto →</a></div></div></body></html>',
'Email po wygaśnięciu okresu próbnego'),

('new_lead', 'Nowy lead: {{leadName}} — {{businessName}}',
'<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f8faf8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;"><div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.06);"><div style="background:linear-gradient(135deg,#3CBF4A,#2EA03A);padding:24px 32px;"><h1 style="color:white;font-size:20px;margin:0;">Nowy lead</h1></div><div style="padding:32px;"><p style="font-size:15px;color:#52525b;margin:0 0 20px;">Twój asystent AI zebrał nowy lead:</p><p style="font-size:14px;color:#52525b;"><strong>Imie:</strong> {{leadName}}</p><p style="font-size:14px;color:#52525b;"><strong>Telefon:</strong> {{leadPhone}}</p><p style="font-size:14px;color:#52525b;"><strong>Zainteresowanie:</strong> {{leadInterest}}</p><a href="{{dashboardUrl}}" style="display:inline-block;background:#3CBF4A;color:white;padding:12px 24px;border-radius:10px;font-size:14px;font-weight:600;text-decoration:none;margin-top:16px;">Zobacz w panelu →</a></div></div></body></html>',
'Powiadomienie o nowym leadzie'),

('churn_prevention', 'Co się dzieje? Brak połączeń od 7 dni — {{businessName}}',
'<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f8faf8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;"><div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.06);"><div style="background:linear-gradient(135deg,#3CBF4A,#2EA03A);padding:32px;text-align:center;"><h1 style="color:white;font-size:24px;margin:0;">Brak aktywności</h1></div><div style="padding:32px;"><h2 style="font-size:20px;color:#171717;margin:0 0 16px;">Cześć {{businessName}},</h2><p style="font-size:15px;color:#52525b;line-height:1.6;margin:0 0 24px;">Zauważyliśmy, że od 7 dni nie było żadnej rozmowy w Twoim asystencie AI. Czy wszystko działa prawidłowo?</p><a href="{{dashboardUrl}}" style="display:inline-block;background:#3CBF4A;color:white;padding:14px 32px;border-radius:12px;font-size:15px;font-weight:600;text-decoration:none;">Przejdź do panelu →</a></div></div></body></html>',
'Retention email po 7 dniach bez połączeń')
ON CONFLICT (key) DO NOTHING;
