INSERT INTO email_templates (key, subject, html, description) VALUES

('auto_topup_success', '✅ Doładowano {{packSize}} min (auto-topup) — {{businessName}}',
'<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f8faf8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;"><div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.06);"><div style="background:linear-gradient(135deg,#3CBF4A,#2EA03A);padding:24px 32px;text-align:center;"><h1 style="color:white;font-size:20px;margin:0;">Automatyczne doładowanie</h1></div><div style="padding:32px;"><h2 style="font-size:18px;color:#171717;margin:0 0 16px;">Doładowano {{packSize}} minut</h2><p style="font-size:15px;color:#52525b;line-height:1.6;margin:0 0 24px;">Automatycznie doładowaliśmy Twoje konto w WitaLine:</p><div style="background:#f0fdf4;border-radius:12px;padding:16px;margin:0 0 24px;"><p style="font-size:14px;color:#1C6323;margin:0 0 4px;"><strong>Pakiet:</strong> {{packSize}} min</p><p style="font-size:14px;color:#1C6323;margin:0 0 4px;"><strong>Kwota:</strong> {{amount}} PLN brutto</p><p style="font-size:14px;color:#1C6323;margin:0;"><strong>Aktualne saldo:</strong> {{balance}} min</p></div><a href="{{dashboardUrl}}" style="display:inline-block;background:#3CBF4A;color:white;padding:12px 24px;border-radius:10px;font-size:14px;font-weight:600;text-decoration:none;">Zobacz konto →</a></div></div></body></html>',
'Potwierdzenie udanego auto-doładowania'),

('auto_topup_failed', '❌ Auto-topup nieudany — {{businessName}}',
'<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f8faf8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;"><div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.06);"><div style="background:linear-gradient(135deg,#EF4444,#DC2626);padding:24px 32px;text-align:center;"><h1 style="color:white;font-size:20px;margin:0;">Błąd automatycznego doładowania</h1></div><div style="padding:32px;"><h2 style="font-size:18px;color:#171717;margin:0 0 16px;">Nie udało się doładować konta</h2><p style="font-size:15px;color:#52525b;line-height:1.6;margin:0 0 24px;">Automatyczne doładowanie dla {{businessName}} nie powiodło się. Auto-topup został wyłączony.</p><div style="background:#fef2f2;border-radius:12px;padding:16px;margin:0 0 24px;"><p style="font-size:14px;color:#991b1b;margin:0;"><strong>Błąd:</strong> {{errorMessage}}</p></div><p style="font-size:14px;color:#52525b;line-height:1.6;margin:0 0 24px;">Sprawdź kartę płatniczą w panelu i włącz automatyczne doładowanie ponownie.</p><a href="{{dashboardUrl}}" style="display:inline-block;background:#3CBF4A;color:white;padding:12px 24px;border-radius:10px;font-size:14px;font-weight:600;text-decoration:none;">Sprawdź konto →</a></div></div></body></html>',
'Błąd automatycznego doładowania'),

('auto_topup_no_card', '🔔 Auto-topup wyłączony — brak karty — {{businessName}}',
'<!DOCTYPE html><html><head><meta charset="utf-8"></head><body style="margin:0;padding:0;background:#f8faf8;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,sans-serif;"><div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 2px 12px rgba(0,0,0,0.06);"><div style="background:linear-gradient(135deg,#F59E0B,#D97706);padding:24px 32px;text-align:center;"><h1 style="color:white;font-size:20px;margin:0;">Brak karty płatniczej</h1></div><div style="padding:32px;"><h2 style="font-size:18px;color:#171717;margin:0 0 16px;">Auto-topup wymaga karty</h2><p style="font-size:15px;color:#52525b;line-height:1.6;margin:0 0 24px;">Automatyczne doładowanie dla {{businessName}} zostało wyłączone, ponieważ nie znaleziono zapisanej karty płatniczej.</p><p style="font-size:14px;color:#52525b;line-height:1.6;margin:0 0 24px;">Dodaj kartę w panelu → Stan konta → Automatyczne doładowanie i włącz ponownie.</p><a href="{{dashboardUrl}}" style="display:inline-block;background:#3CBF4A;color:white;padding:12px 24px;border-radius:10px;font-size:14px;font-weight:600;text-decoration:none;">Dodaj kartę →</a></div></div></body></html>',
'Brak karty do automatycznego doładowania')

ON CONFLICT (key) DO NOTHING;
