ALTER TABLE conversations ADD COLUMN IF NOT EXISTS flagged BOOLEAN DEFAULT false;
ALTER TABLE conversations ADD COLUMN IF NOT EXISTS flag_color TEXT DEFAULT NULL;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS flagged BOOLEAN DEFAULT false;
ALTER TABLE call_logs ADD COLUMN IF NOT EXISTS flag_color TEXT DEFAULT NULL;
