ALTER TABLE businesses ADD COLUMN IF NOT EXISTS industry TEXT DEFAULT '';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS website_url TEXT DEFAULT '';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT '';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS stripe_subscription_id TEXT;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS subscription_status TEXT DEFAULT 'incomplete';
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS suspended BOOLEAN DEFAULT false;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS reseller_id UUID;
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS reseller_markup NUMERIC(5,2) DEFAULT 0;
